### ISSUE TITLE
No-impact bug in the RoutingTable constructor

### ISSUE THREAD

**Issue by smoyer64** [mafintosh/kademlia-routing-table#2]
The length of the array holding row data in the `RoutingTable` constructor is currently:

```
this.rows = new Array(id.length * 8 - 1)
```

but it should be:

```
this.rows = new Array(id.length * 8)
```

According to the [Kademlia](https://en.wikipedia.org/wiki/Kademlia) article on Wikipedia:

> With an ID of 128 bits, every node in the network will classify other nodes in one of 128 different distances, one specific distance per bit.

The existing implementation of `_diff()` is correct but will initially return an index of that's two less than the number of id bits if the table's key is passed into the function.  And initially, this has no adverse effects because no nodes are only one bit away from the table (in fact, there's only one node that can be that close and with long random key lengths, it's statistically unlikely that there would ever be a node with that id).

As implemented, this bug is self-correcting in JavaScript - if a node that's one bit away from the table's id is ever encountered, the `add()` function will accept an index that's greater than the initial size of the array and the row will be created.  At that point, the index returned by `_diff()` if the table's id is passed in will point to this newly added row.

Since this is the reference implementation used for HyperSwarm, I'd suggest changing the constructor as noted above.  This will certainly help those of us who are using other languages (where arrays don't have "mapiness").

**Comment by mafintosh** [comment]
If all bits are shared, ie diff = id.length * 8, aren't the node you're looking for yourself and you shouldn't add it? that's at least the logic behind it.

**Comment by smoyer64** [comment]
Let's say the IDs are 16 bits long - there are 17 possible states from 0 to 16 leading zeroes.  If the incoming ID matches the table ID, `_diff()` correctly subtracts 1 from the result and returns the index for the row with one bit difference.  So if the table has 16 rows, it matches the quoted behavior from Kademlia and it matches what `_diff()` does.  The early return would still only return indexes from 0 to 14.

**Comment by mafintosh** [comment]
Sorry I don’t follow. Do you have a code example that illustrates this? That might make it easier to grok

**Comment by smoyer64** [comment]
A code example against the public methods in `kademlia-routing-table` won't actually show an error because the size of the rows array will be increased from `n-1` to `n` where `n` is the number of bits in the table's id.  As an example, let's pick a short table id of 0x0000 so that the result of the XOR operation is equal to the id being compared.  The (initial) length of the rows table will be `16-1=15`.  The table below shows the output of the `_diff()` function for each prefix length along with whether the function returned due to a bit difference or due to the incoming id being equal to the table id.

```
10000000 00000000 : 0 (diff)
01000000 00000000 : 1 (diff)
00100000 00000000 : 2 (diff)
00010000 00000000 : 3 (diff)
00001000 00000000 : 4 (diff)
00000100 00000000 : 5 (diff)
00000010 00000000 : 6 (diff)
00000001 00000000 : 7 (diff)
00000000 10000000 : 8 (diff)
00000000 01000000 : 9 (diff)
00000000 00100000 : 10 (diff)
00000000 00010000 : 11 (diff)
00000000 00001000 : 12 (diff)
00000000 00000100 : 13 (diff)
00000000 00000010 : 14 (diff)
00000000 00000001 : 15 (diff) - index out-of-bounds
00000000 00000000 : 14 (equal) - incoming id equals table id
```

So my assertion is that the `_diff()` function is correct (and matches the documentation I've found for Kademlia routing tables).  The indexes returned from line 88 (https://github.com/mafintosh/kademlia-routing-table/blob/1c1b290921bcfce510c2521f14aaddc4c0366e48/index.js#L88) range from `0-15` but since the initial size of the table is `15`, that would result in an index out-of-bounds.  The way this is implemented, if an id that was only one bit away from the table's id was ever encountered, the `add()` function would silently "append" a sixteenth row to the table and there would be no error.

I think the idea behind the line 91 (https://github.com/mafintosh/kademlia-routing-table/blob/1c1b290921bcfce510c2521f14aaddc4c0366e48/index.js#L91) is that if the table's own id is ever added to the table, it will put it in the row representing the absolute closest nodes and you could end up with both the table's id and the single id with the one bit different (that row would normally never have more than one node but now might have two).  I'm still thinking through whether we would ever want our own node id in the table.

**Comment by mafintosh** [comment]
If you have code that show the dynamic array growth, share it - it doesn't matter that it recovers, lets me see the behaviour easily. Will try to grok what you read.

**Comment by mafintosh** [comment]
Are you saying an insertion of a key that is 1 bit away from the table id causes this?

**Comment by smoyer64** [comment]
Yes ... since the table is n (bit length) -1 rows to start, it's not big enough to include (one) node that might be 1 bit away from the table id.  So if you fix the line I mentioned at the very top of this issue, there's already a row for that node and (maybe more importantly), the index returned from `_diff()` when the table's own id is passed in is equal to the next closest node.

**Comment by mafintosh** [comment]
Bumped the size to id.length * 8 - it should never dynamically grow - ever. If you see that send a test case.
